# Copyright 2019 Carbon Black Inc.  All rights reserved. 
#
# Makefile for the dynamic security module
#
# To avoid collisions with other modules based on this source, set the 
# DYNSEC_BRAND environment variable before building to give the output
# module a unique name and identity.
#
ifeq ($(DYNSEC_BRAND),)
        DYNSEC_BRAND = generic
endif

EXTRA_CFLAGS += "-DDYNSEC_BRAND=$(DYNSEC_BRAND)" "-DDYNSEC_STRING=\"$(DYNSEC_BRAND)\"" -I. 
DESTDIR ?= $(PWD)
OUTPUT_KO ?= dyn_sec_$(DYNSEC_BRAND).ko

ifeq ($(KVERSION),)
	KVERSION = $(shell uname -r)
endif

ifeq ($(KBUILD_DIR),)
	KBUILD_DIR := /lib/modules/$(KVERSION)/build
endif

ifeq ($(OUTPUT_DIR),)
        OUTPUT_DIR := $(DESTDIR)/stage/$(shell uname -i)/$(KVERSION)
endif

obj-m += dyn_sec_$(DYNSEC_BRAND).o
dyn_sec_$(DYNSEC_BRAND)-objs := dyn-sec.o opcache.o usercomm.o


PWD := $(shell pwd)

all:
	@$(MAKE) --no-print-directory -C $(KBUILD_DIR) M=$(PWD) $(VERBOSE) modules
	@echo "Staging dyn_sec_$(DYNSEC_BRAND).ko to $(OUTPUT_DIR)"; \
	mkdir -p $(OUTPUT_DIR)/; \
	cp dyn_sec_$(DYNSEC_BRAND).ko $(OUTPUT_DIR)/dyn_sec_$(DYNSEC_BRAND).ko$; \

clean:
	@$(MAKE) --no-print-directory -C $(KBUILD_DIR) M=$(PWD) clean

distclean: clean
	rm -rf $(DESTDIR)

# endif
